//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MunshiDAL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MunshiDAL.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - .
        /// </summary>
        internal static string Dash {
            get {
                return ResourceManager.GetString("Dash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;&gt;&gt;.
        /// </summary>
        internal static string EnterProc {
            get {
                return ResourceManager.GetString("EnterProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while creating {0}.
        /// </summary>
        internal static string ErrorCreatingElement {
            get {
                return ResourceManager.GetString("ErrorCreatingElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while Deleting {0}.
        /// </summary>
        internal static string ErrorDeletingElement {
            get {
                return ResourceManager.GetString("ErrorDeletingElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in - .
        /// </summary>
        internal static string ErrorIn {
            get {
                return ResourceManager.GetString("ErrorIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while updating {0}.
        /// </summary>
        internal static string ErrorUpdatingElement {
            get {
                return ResourceManager.GetString("ErrorUpdatingElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;&lt;&lt;.
        /// </summary>
        internal static string ExitProc {
            get {
                return ResourceManager.GetString("ExitProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This {0} had been deleted. Please recheck..
        /// </summary>
        internal static string InfoDataDeleted {
            get {
                return ResourceManager.GetString("InfoDataDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data has been changed. Hence not updating in database..
        /// </summary>
        internal static string InfoNoDataChanged {
            get {
                return ResourceManager.GetString("InfoNoDataChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} has been successfully created..
        /// </summary>
        internal static string InfoSuccessfullyCreated {
            get {
                return ResourceManager.GetString("InfoSuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} has been successfully deleted..
        /// </summary>
        internal static string InfoSuccessfullyDeleted {
            get {
                return ResourceManager.GetString("InfoSuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} has been successfully updated..
        /// </summary>
        internal static string InfoSuccessfullyUpdated {
            get {
                return ResourceManager.GetString("InfoSuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the page data.
        /// </summary>
        internal static string PageLoadError {
            get {
                return ResourceManager.GetString("PageLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Timeout.
        /// </summary>
        internal static string SessionTimeOut {
            get {
                return ResourceManager.GetString("SessionTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SessionVariables.
        /// </summary>
        internal static string SessionVariableName {
            get {
                return ResourceManager.GetString("SessionVariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has been deleted.
        /// </summary>
        internal static string WarnRecordHasBeenDeleted {
            get {
                return ResourceManager.GetString("WarnRecordHasBeenDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has been updated.
        /// </summary>
        internal static string WarnRecordHasBeenUpdated {
            get {
                return ResourceManager.GetString("WarnRecordHasBeenUpdated", resourceCulture);
            }
        }
    }
}
